# Usar la imagen oficial de PHP 8 con Apache
FROM php:8.2-apache
# Instalar extensiones de PHP necesarias
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    && docker-php-ext-install zip
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql
# Instalar Composer globalmente
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# Configurar el directorio de trabajo

WORKDIR /var/www/html
RUN a2enmod rewrite
COPY src/ /var/www/html
EXPOSE 8000
EXPOSE 80
